### ISSUE TITLE
Mapas [Tarea]

### ISSUE THREAD

**Issue by gamerevar** [gamerevar/proyecto-comunitario-1-unity#18]
Mapas

## Cómo serán los mapas?

- Ancho y alto?
- Tipos de terreno?

### Referencias

[Codecks](https://open.codecks.io/proyecto-comunitario-1-unity/decks/17-game-design/card/13i-mapas)

**Comment by LeoMast** [comment]
Lo ideal es que el mapa mida, a falta de una unidad de medida mejor,   1 pantalla y media o 2 pantallas de ancho y  3 pantallas de alto. 

Con respecto al terreno. Se definió  el primer nivel y el ultimo, mínimo se requiere de un nivel mas el cual será compartido con el juego de Godot para hacer una buena referencia entre los juegos.

**Comment by gamerevar** [comment]
Lo cerramos a este issue ya que puede definirse en el #41.
