### ISSUE TITLE
Movimiento del Dron [Tarea]

### ISSUE THREAD

**Issue by gamerevar** [gamerevar/proyecto-comunitario-1-unity#21]
# Movimiento del Dron

* Crear un script llamado DroneMovement.cs en el directorio Assets/Drone
* Asignar el script al objeto llamado "Drone" en la escena Prototype.
* El script primero deberia obtener una referencia al Jugador. Esto puede ser a travez de una referencia publica u obteniendo el objeto del jugador con el metodo GameObject.FindWithTag.
* Luego el dron deberia moverse activamente para acercarse al jugador hasta cierta distancia, la cual puede estar dada por un float publico distance. (esto para evitar que el Dron se pegue muy encima del Jugador)
* Una forma facil de lograr un movimiento seria con el metodo Transform.Translate.
* Asegurarse de que el movimiento sea framerate-independent.
* La velocidad de movimiento del dron puede estar dada por un float publico speed.

### Referencias

[Codecks](https://open.codecks.io/proyecto-comunitario-1-unity/decks/10-programación/card/14i-movimiento-del-dron)

**Comment by gamerevar** [comment]
Pudiste avanzar @NNmac? Acá podés solicitar ayuda de ser necesario.

**Comment by Svartskogen** [comment]
Cierro el issue por que se asigno a la PR luego de que la apruebe
