### ISSUE TITLE
Calculo de punto de disparo [Tarea]

### ISSUE THREAD

**Issue by Svartskogen** [gamerevar/proyecto-comunitario-1-unity#25]
# Calculo de punto de disparo

Esta tarea quizas sea un poco complicada/confusa.
Hay que crear un script que se encargue de rotar constantemente un objeto hacia la posicion del mouse, esto nos va a ayudar luego para poder instanciar proyectiles desde la posicion del dron y heredar la rotacion del **DroneShootPivot**, asi los proyectiles apuntarian correctamente a la posicion del mouse.

- Crear un script, llamado **RotateTowardsMouse.cs,** en la carpeta Assets/Scripts/Misc.
- Asignarle el script al objeto DroneShootPivot (hijo de Drone)
- El script debe rotar el objeto actual hacia donde apunta el mouse, algo que se puede lograr de varias formas y suele involucrar calculos complejos.
- Para facilitar la tarea, voy a proveer un Script que hace algo parecido, rota un objeto hacia la **posicion** de otro. (ver Gist abajo), primero habria que entender como funciona el script para luego adaptarlo y que en vez de usar la posicion de otro objeto (_target_ en la referencia), tome la posicion del mouse (ver [Input.mousePosition](https://docs.unity3d.com/ScriptReference/Input-mousePosition.html)).
- Como referencia, queremos que el **transform.right** del **DroneShootPivot** apunte hacia el mouse, esto lo pueden comprobar en Unity asegurandose de que la flecha **roja** (Esto se lograria ajustando ese -90 en la linea 9 del Gist)
### Referencias
[Gist con script de referencia](https://gist.github.com/Svartskogen/d1285bea6251172fbfa23a0ea8bebfe4)

**Comment by NNmac** [comment]
Ahí ajuste el script que pasaste, dejo el pull request.
