### ISSUE TITLE
Primer Nivel completada[Tarea]

### ISSUE THREAD

**Issue by LeoMast** [gamerevar/proyecto-comunitario-1-unity#27]
# Primer Nivel 

**Primer nivel**
El jugador sale desde su pueblo ( por favor corregir esto, es un pueblo no una tribu, ya que tribu suena mas a indigena y estas personas son más desarrolladas)
El jugador es enviado a buscar un antiguo templo en el cual seguramente se encuentra la solución a los problemas que actualmente sufren,

El primer nivel es una pradera donde el jugador encontrará algunos enemigos que interrumpen su paso y luego encontrará aún más enemigos a medida que recorre el nivel. Los enemigos son grandes felinos mutantes,
 ( para el equipo de arte, estas mutaciones pueden ser aberraciones donde ejemplo un Leopardo sufrió mutaciones y se fusionó a restos de tecnología antigua, realmente me gusto este boceto ------->

![Felino](https://user-images.githubusercontent.com/33333092/103464892-fd0be800-4d15-11eb-9c84-0772da2c5ae5.png)

Esta pradera se ve y siente bien aunque hay algunas secuelas de la guerra nuclear, pueden ser restos de vehículos de tierra o aire,  grandes pozos ( con pasto, flores o lo que sea pasaron 200 años)  secuela de que algo explotó allí.

El mapa debe tener tal dimensión que permita al jugador moverse en cualquier dirección ( con que sea 2 o 3 pantallas de ancho y el doble de alto está bien. la idea es que el jugador  avance,( algún nivel hacia arriba y otro hacia otro lado ejemplo, en el nivel 2 el mapa tendría 2 o 3 pantallas de alto pero 5 o 6 de ancho y el jugador avanza hacia la izquierda o derecha) podría ser algo así  ---------> 

![Pradera](https://user-images.githubusercontent.com/33333092/103464905-1f056a80-4d16-11eb-93e5-873c026c8ea3.jpg)

Esta pradera se ve y siente bien aunque hay algunas secuelas de la guerra nuclear, pueden ser restos de vehículos de tierra o aire,  grandes pozos ( con pasto, flores o lo que sea pasaron 200 años)  secuela de que algo explotó allí.

**El mapa** debe tener tal dimensión que permita al jugador moverse en cualquier dirección ( con que sea 2 o 2.5 pantallas de ancho y el doble de alto está bien. la idea es que el jugador  avance,( algún nivel hacia arriba y otro hacia otro lado ejemplo, en el nivel 2 el mapa tendría 2 o 2.5 pantallas de alto pero 4 o 5 de ancho y el jugador avanza hacia la izquierda o derecha) podría ser algo así  ---------> 

![Shadowgrounds](https://user-images.githubusercontent.com/33333092/103464932-4d834580-4d16-11eb-981c-25f97a7087d9.png)

Y la distancia de la cámara debería ser un punto intermedio entre la imagen de arriba y la siguiente:

![Muy alta la camara](https://user-images.githubusercontent.com/33333092/103464941-64299c80-4d16-11eb-89c9-fa60c869bf1f.png)

El objetivo de este nivel es simplemente eliminar a todos los enemigos. Una vez cumplido termina el nivel con un cartel, si se quiere, de felicitación o que aclare que el nivel fue completado y se pasa a la cutscene.

**Mecánicas** 

El player se moverá con wasd y sobre él lo seguirá su Dron el cual dispara hacia la posición del mouse, en futuros niveles el Dron podrá disparar dos armas ( una con cada botón del mouse)
El Dron posee 2 armas. La primera es un láser y la segunda es un lanzador de pequeños cristales sobrecargados que explotan al impactar contra algo. 

El jugador no tiene armas y puede realizar un Dash para evadir a los enemigos que tiene muy cerca. La idea es que pueda hacer dash en cualquier dirección. 

El enemigo en este nivel es ágil y realiza un ataque tipo melee, salta hacia el jugador y lanza un zarpazo. ( es claro que el enemigo y su ataque se repetirá en los sucesivos niveles)

**Comment by gamerevar** [comment]
fixes: $13f
