### ISSUE TITLE
Enemigos Completada [Tarea]

### ISSUE THREAD

**Issue by LeoMast** [gamerevar/proyecto-comunitario-1-unity#30]
# Enemigos

Hay 4 enemigos por el momento. 
Felinos mutantes aparecen en los primeros niveles. 
Raides aparecen en niveles intermedios junto con los Felinos mutantes.
Robots aparecen en los últimos niveles junto con los raides y en menor cantidad los Felinos mutantes.
Robots Guardianes aparecen en los niveles dentro del templo junto con los Felinos mutantes.

Stats

  | Felino Mutante |   |  
-- | -- | -- | --
Vida | 80 |   |   |  
Agilidad | 8 |   |   |  
Armas | Daño | Alcance | Cadencia |  
Ataque melle | 10 | 1 de 6 | 1 cada 3 seg |  
Comportamiento | Ataque rápidamente cuando se encuentra a una distancia de 4 de 6 |  

  | Raider |   |  
-- | -- | -- | --
Vida | 100 |   |   |  
Agilidad | 6 |   |   |  
Armas | Daño | Alcance | Cadencia |  
Laser | 25 | 4 de 6 | 1 cada 2 seg |  
Comportamiento | Va en busca del player al estar a una distancia de 5 de 6 |  

  | Robot |   |  
-- | -- | -- | --
Vida | 150 |   |   |  
Agilidad | 3 |   |   |  
Armas | Daño | Alcance | Cadencia |  
Cañón laser | 25 | 5 de 6 | 1 cada 4 seg |  
Comportamiento | Ataca al player al estar a una distancia de 5 de 6 acercándose solo para estar en alcance para disparar |  

  | Robot Guardian |   |  
-- | -- | -- | --
Vida | 250 |   |   |  
Agilidad | 4 |   |   |  
Armas | Daño | Alcance | Cadencia |  
Cañon laser | 30 | 6 de 6 | 1 cada 4 seg |  
Golpe paralizante | 10 | 2 de 6 | 1 cada 2 seg |  
Comportamiento | Ataca al player al estar a una distancia de 6 de 6. intenta hacercarse para paralizar al player |  

Corresponde a la card https://gamerev.codecks.io/card/13j-enemigos

**Comment by gamerevar** [comment]
Se cierra el issue. Los guardianes del templo son los mismos que los guardianes tecnomágicos del proyecto Godot, por lo tanto no se pueden determinar aun. Eso lo veremos mas adelante.
