### ISSUE TITLE
Mapa del Templo [Tarea]

### ISSUE THREAD

**Issue by LeoMast** [gamerevar/proyecto-comunitario-1-unity#35]
# Templo Mapa

El plano del Mapa del templo.
No hace falta la animación de la puerta que se abre.
Los cuadrados que tienen una Letra Son palancas o botones para abrir las puertas con la misma Letra. Ejemplo. El cuadrado con la letra A es una palanca que abre la puerta con la letra A.
![Mapa Templo](https://user-images.githubusercontent.com/33333092/104188651-518b2380-53f8-11eb-84df-e138e528188a.jpeg)

Las 2 puertas que tienen líneas de puntos ya están abiertas en el aspecto gráfico
Las otras 3 están cerradas. Y cuando el jugador activa "el botón o palanca" se abren. Pero están lejos así que cuando llega a la puerta ya la ve abierta
Para tener una idea de la dimensión del mapa el cuadrado del medio que tiene 10 enemigos deberia tener el ancho de una pantalla de monitor aproximadamente,

**Comment by gamerevar** [comment]
Asignado a arte para diseñar los tiles y sprites necesarios para el prototipo de nivel.

**Comment by gamerevar** [comment]
Esta tarea está repetida en el issue #41.

Se cierra el issue y vamos a dejarlos linkeados.
