### ISSUE TITLE
Disparo del Dron

### ISSUE THREAD

**Issue by Svartskogen** [gamerevar/proyecto-comunitario-1-unity#51]
### Disparo del Dron
Los últimos días fueron avanzando muy bien con las tareas y esta ya estaría siendo una de las ultimas para finalizar esta primera fase de prototipado.
Esta vez voy a definir a grandes rasgos la implementación, eso si aclarando bien el funcionamiento por que el [GDD](https://open.codecks.io/proyecto-comunitario-1-unity/decks/23-mec%C3%A1nicas-del-juego/card/12s-dron) quizás hace confusas las diferencias entre uno y otro.
Básicamente el Dron tiene 2 disparos: un laser y un "lanza cristales", ambos serian proyectiles físicos que se mueven a alta velocidad (seguramente el laser va a ser muchísimo mas rápido, mientras que el cristal mas lento).
Para esto vamos a tener que definir un script llamado **Proyectile.cs** también, el cual va a tener información sobre el daño y velocidad de movimiento del mismo.
Y por ultimo hay que tener en cuenta las capas de colisión, esto lo voy a commitear ahora mismo así no se suma mucho trabajo a la tarea.
Entonces a grandes rasgos lo que hay que hacer es:

- Crear 2 scripts:
   - **DroneAttack.cs** en **Assets/Scripts/Drone**
   - **Proyectile.cs** en **Assets/Scripts/Misc**
- **DroneAttack.cs** debe cumplir con la siguiente funcionalidad:
   - Almacenar 2 GameObjects publicos (prefabs de los 2 tipos de proyectiles)
   - Almacenar y manejar la cadencia de disparo de los 2 tipos de proyectiles
   - Instanciar los proyectiles con la rotación correspondiente (acordarse del pivot, el cual siempre apunta a la posicion del mouse)
- **Proyectile.cs** debe cumplir con la siguiente funcionalidad:
   - Disponer de variables publicas (o privadas serializadas) para almacenar los valores del daño, alcance y velocidad del proyectil
   - Detectar la colisión con otro objeto y en el caso de que colisione con un objeto cuya tag sea "Enemy", acceder a su componente **Enemy.cs**, dañarlo según el daño del proyectil y destruir el proyectil mismo.
- El aspecto de un proyectil seria el siguiente:
   - Un objeto con un SpriteRenderer, un BoxCollider2D, RigidBody2D (asegurarse de usar la opción **continua** para detección de colisiones y su respectivo **Proyectile.cs**.
   - Estos proyectiles, al ser lanzados por el Drone, deberian ir en la layer **_PlayerBullet_**, la cual colisiona con todo menos con el jugador
- Crear 2 prefabs, uno para cada tipo de proyectil, asignarle el script DroneAttack.cs al Drone en la escena de prototipo y llenar los prefabs correspondientes.

Para los valores de los prefabs pueden intentar de copiar lo que sugiere el GDD y para las velocidades a ojo ya que no las especifican.

Esta es una tarea bastante larga y puede que se me haya salteado algún detalle, cualquier cosa me van consultando por Discord.

Aca cito tal cual lo describe el [GDD](https://open.codecks.io/proyecto-comunitario-1-unity/decks/23-mec%C3%A1nicas-del-juego/card/12s-dron):

#### Segun el GDD:
El Dron posee 2 armas: un láser y un lanzador de pequeños cristales que explotan al impactar contra algo y su disparo es controlado con los botones del mouse.
#### Láser
Daño: 20
Alcance: 4/6 tiles
Cadencia: 1 seg.
Se activa con click izquierdo

###3 Lanza cristales
Daño: 35
Alcance: 2/6 tiles
Cadencia: 4 seg.
Se activa con click derecho

**Comment by Svartskogen** [comment]
IMPORTANTE: El lanza cristales debe hacer daño en area, lo dejamos para otra tarea luego, por ahora solo existiria un tipo de proyectil

**Comment by Cundalf** [comment]
Duda: El tema del alcance lo hice en relacion al tiempo o la idea es hacerlo literal por distancia recorrida?

**Comment by Svartskogen** [comment]
Si, la idea es hacerlo por distancia recorrida, asi podemos modificar la velocidad sin que se modifique el alcance

**Comment by Cundalf** [comment]
Joya, entonces lo saco y queda para otra issue
