### ISSUE TITLE
Movimiento del jugador [FEATURE]

### ISSUE THREAD

**Issue by Svartskogen** [gamerevar/proyecto-comunitario-1-unity#7]
**Descripción del feature**
Programar un sistema de movimiento simple para el jugador interactuando con su RigidBody2D

**Razón del feature**
El movimiento del jugador es una mecanica esencial del juego.

**Implementación del feature**

- Crear un script llamado PlayerMovement.cs en el directorio Assets/Scripts/Player
- Asignar el script al objeto llamado "Player" en la escena Prototype.
- El script deberia tomar los valores de los ejes "Horizontal" y "Vertical" usando el metodo GetAxis (o GetAxisRaw) de la clase Input ([Documentación](https://docs.unity3d.com/ScriptReference/Input.GetAxis.html))
- Modificar directamente el Vector2 velocity del RigidBody2D ([Documentación](https://docs.unity3d.com/ScriptReference/Rigidbody2D-velocity.html)) en base a los valores dados por el Input.
- Asegurarse de normalizar el vector direccion calculado en base al Input.

**Comment by gamerevar** [comment]
Tarea creada!

[ver tarea](https://open.codecks.io/proyecto-comunitario-1-unity/decks/10-programación/card/14j-movimiento-del-jugador)
