### ISSUE TITLE
Movimiento del Dron [FEATURE]

### ISSUE THREAD

**Issue by Svartskogen** [gamerevar/proyecto-comunitario-1-unity#9]
**Descripción del feature**
Programar un script encargado de mover el dron, siguiendo al jugador.

**Razón del feature**
El dron debe seguir de cerca al jugador, ya que este es el que va a disparar.

**Implementación del feature**

- Crear un script llamado DroneMovement.cs en el directorio Assets/Drone
- Asignar el script al objeto llamado "Drone" en la escena Prototype.
- El script primero deberia obtener una referencia al Jugador. Esto puede ser a travez de una referencia publica u obteniendo el objeto del jugador con el metodo [GameObject.FindWithTag](https://docs.unity3d.com/ScriptReference/GameObject.FindWithTag.html).
- Luego el dron deberia moverse activamente para acercarse al jugador hasta cierta distancia, la cual puede estar dada por un float publico _distance_. (esto para evitar que el Dron se pegue muy encima del Jugador)
- Una forma facil de lograr un movimiento seria con el metodo [Transform.Translate](https://docs.unity3d.com/ScriptReference/Transform.Translate.html).
- Asegurarse de que el movimiento sea **framerate-independent**.
- La velocidad de movimiento del dron puede estar dada por un float publico _speed_.

**Comment by gamerevar** [comment]
related: $14i
